### PR TITLE
Vite Integration and React Entry Point 

### PR DESCRIPTION
**Pull request by nwalker2398**
Finished migrating assets imports to use Vite and removed the importmap gem from the repo. 
Finished adding React to repo and creating a React entry point for the cart display—currently a placeholder React component for this is visible at the bottom of item page).

A Vite console warning remains (apparently only visible in Safari and not Chrome), but Eric and I agree that it is benign and should be only visible in a development environment.

### CODE REVIEW

**Comment by bonniegee** [comment]
Thank you @nwalker2398 ! I'm trying to get this up an running following the README instructions (thank you for adding those), but am getting stuck between steps 1 and 2. I installed nvm with homebrew and then ran "yarn install" from a new tab in my terminal, but am getting "yarn not installed." Is there something additional that I need to do?

**Comment by nwalker2398** [comment]
> Thank you @nwalker2398 ! I'm trying to get this up an running following the README instructions (thank you for adding those), but am getting stuck between steps 1 and 2. I installed nvm with homebrew and then ran "yarn install" from a new tab in my terminal, but am getting "yarn not installed." Is there something additional that I need to do?

You should be able to run `npm install --global yarn` to fix this—I updated the README with this instruction as well.

**Comment by bonniegee** [comment]
That worked, thank you @nwalker2398 ! 

On the home page I'm seeing a weird box underneath the search bar -- let me know if there's more info I can provide: 
Screen Shot 2024-04-15 at 12 21 58 PM

I am also unable to load the collection contents sidebar:
Screen Shot 2024-04-15 at 12 23 47 PM

Are either of those happening for you? Is there anything I should look for using developer tools?

**Comment by nwalker2398** [comment]
> That worked, thank you @nwalker2398 !
> 
> On the home page I'm seeing a weird box underneath the search bar -- let me know if there's more info I can provide: Screen Shot 2024-04-15 at 12 21 58 PM
> 
> I am also unable to load the collection contents sidebar: Screen Shot 2024-04-15 at 12 23 47 PM
> 
> Are either of those happening for you? Is there anything I should look for using developer tools?

Yes I've got the weird box, I'm looking at the page source right now to track that down. How do I load the collections sidebar though? I'm trying to find it on the prod Findingaids app to compare and can't figure out where it is

**Comment by bonniegee** [comment]
@nwalker2398 Prod & test have v1.x of the app, dev has full Arclight. Any finding aid here should have a collection contents sidebar: https://findingaids-dev.library.columbia.edu/archives?f%5Blevel%5D%5B%5D=File&group=true

**Comment by nwalker2398** [comment]
> @nwalker2398 Prod & test have v1.x of the app, dev has full Arclight. Any finding aid here should have a collection contents sidebar: https://findingaids-dev.library.columbia.edu/archives?f%5Blevel%5D%5B%5D=File&group=true

Thanks, yes I see it now, and my version is also not showing the contents. I'm checking which commit caused these issues.

**Comment by nwalker2398** [comment]
> > That worked, thank you @nwalker2398 !
> > On the home page I'm seeing a weird box underneath the search bar -- let me know if there's more info I can provide: Screen Shot 2024-04-15 at 12 21 58 PM
> > I am also unable to load the collection contents sidebar: Screen Shot 2024-04-15 at 12 23 47 PM
> > Are either of those happening for you? Is there anything I should look for using developer tools?
> 
> Yes I've got the weird box, I'm looking at the page source right now to track that down. How do I load the collections sidebar though? I'm trying to find it on the prod Findingaids app to compare and can't figure out where it is

Collection contents loading fixed in latest commit, working to resolve the weird box now.

**Comment by nwalker2398** [comment]
Ok, weird box appears to be the [autocomplete popup](https://github.com/projectblacklight/blacklight/blob/6c6a72066a6330a815603e839b316958f6321dd7/app/components/blacklight/search_bar_component.html.erb#L26). Looking into issues with styling that may cause it to not be hidden.

**Comment by nwalker2398** [comment]
@bonniegee I've fixed the weird box issue too now, I think everything may be good to go, pending your review.

**Comment by bonniegee** [comment]
Thank you @nwalker2398 ! I then got this error as a pop up when I opened the app:
Screen Shot 2024-04-15 at 6 26 15 PM

I re-started yarn and ran bundle install beforehand...not sure if I was missing another step?

**Review by bonniegee — APPROVED** [review]
Looks great so far, thank you @nwalker2398 ! Before merging, can you remove the "aasdfadsfdsasfd" placeholder text?

**Comment by nwalker2398** [comment]
> Looks great so far, thank you @nwalker2398 ! Before merging, can you remove the "aasdfadsfdsasfd" placeholder text?

Oh yeah that's probably a good idea—Just removed it in the latest commit

**Pull request merged**
