### PR TITLE
ACFA-500

### PR DESCRIPTION
**Pull request by elohanlon**

### CODE REVIEW

**Review by bonniegee — COMMENTED** [review]
Thank you so much, Eric! I am seeing a weird blank autosuggestion block when the page first loads, for a very brief period. I'm going to try to take a screencast, not sure if you're seeing this behavior too?

**Comment by bonniegee** [comment]
Uploading Screen Recording 2024-05-24 at 5.40.35 PM.mov…

**Comment by bonniegee** [comment]
https://github.com/cul/ldpd-findingaids-asi/assets/8737364/4cc40aba-c70d-4439-a66a-b1835615fae0

**Comment by elohanlon** [comment]
@bonniegee Ah yeah, I see what you mean.  It's actually appearing on the Finding Aids dev and prod sites as well, so it looks like an existing issue that's unrelated to the latest changes.  Out of curiosity, I checked the Arclight demo site (https://arclight-demo.projectblacklight.org) and it appears there as well!

https://github.com/cul/ldpd-findingaids-asi/assets/1017323/f8d8ab35-b05b-4355-b0ca-c27e1da4a701

https://github.com/cul/ldpd-findingaids-asi/assets/1017323/57d7083e-f6ac-4ffe-a0ec-c5f64c57d8ad

https://github.com/cul/ldpd-findingaids-asi/assets/1017323/78e3b73e-ab12-410a-b4b4-888dc5bd3aa2

I'll check this out further.  Thank you for pointing that out!

**Comment by elohanlon** [comment]
@bonniegee I just pushed another commit that should hopefully help!  I overrode a blacklight partial as an immediate fix for us here in Finding Aids, but I've also proposed the change in the Blacklight repo itself: https://github.com/projectblacklight/blacklight/pull/3161

**Review by bonniegee — APPROVED** [review]
Amazing, thank you so much @elohanlon !

**Pull request merged**
