### PR TITLE
In Gemfile, raise error if font_awesome_token is missing

### PR DESCRIPTION
**Pull request by elohanlon**

### CODE REVIEW

**Comment by bonniegee** [comment]
@elohanlon Is it okay if I change the base to [dev-v2.0.0](https://github.com/cul/ldpd-findingaids-asi/tree/dev-v2.0.0) (since this is not directly related to Aeon integration)?

**Comment by elohanlon** [comment]
@bonniegee Sure!  In fact, I'll do that right now!

**Comment by elohanlon** [comment]
And actually, I'll redo my change based on dev-v2.0.0 as the base branch.  Will force push a new commit in just a few minutes.

**Comment by elohanlon** [comment]
@bonniegee Updated!

**Review by bonniegee — APPROVED** [review]

**Pull request merged**
